## Implementation Index

A random assortment of functions and brief implementations across the realm of machine learning

In [3]:
import numpy
import sklearn
import tensorflow as tf
from tensorflow import keras

##### sklearn.utils.shuffle - shuffles its args in exactly the same way

In [12]:
x = numpy.array([0,1,2,3,4,5,6,7,8,9,10])
y = numpy.array(['a','b','c','d','e','f','g','h','i','j','k'])
shuffx, shuffy = sklearn.utils.shuffle(x, y)
print(shuffx, shuffy)

[ 9  3  5  2  1  8  0  6  7  4 10] ['j' 'd' 'f' 'c' 'b' 'i' 'a' 'g' 'h' 'e' 'k']


##### numpy.reshape (equivalent to numpy.ndarray.reshape)

In [19]:
z = numpy.array([[1,2,3],[4,5,6]])
w = numpy.array([1,2,3,4,5])
z.reshape(-1,2)
w.reshape(-1, 1)
print(z)
print(w)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5]


##### numpy.argmax - returns index of max number

In [1]:
predictions = [0.8, 0.2, 0.5, 0.2, 0.9, 0.8]
rounded = numpy.argmax(predictions)
print(rounded)

NameError: name 'numpy' is not defined

##### sklearn.metrics.confusion_matrix - SKlearn's Confusion Matrix implementation

In [9]:
from sklearn.metrics import confusion_matrix
predictions = [1,1,0,0,1,0,1,0,0,0,0,1]
actual      = [1,0,0,1,0,0,1,0,0,0,0,1]

cm = sklearn.metrics.confusion_matrix(y_true=actual, y_pred=predictions)

print(cm)
# [[TN, FP]
#  [FN, TP]]

[[6 2]
 [1 3]]
